# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=150),
            preserve_default=False,
        ),
    ]
