# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[(b'Easy', b'Easy'), (b'Intermediate', b'Intermediate'), (b'Advanced', b'Advanced')], default='Easy', max_length=20),
        ),
    ]
